src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: 'email', message: "C'est email est déjà enregistré")]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    #[Assert\Email(message: "Veuillez renseigner un email valide")]
    #[Assert\NotBlank(message: "Ce champ ne peut être vide")]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    #[Assert\Length(min: 6, minMessage: "Le mot de passe doit faire au minimum 6 caracteres")]
    #[Assert\NotBlank(message: "Ce champ ne peut être vide")]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Ce champ ne peut être vide")]
    private ?string $firstname = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Ce champ ne peut être vide")]
    private ?string $lastname = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Question::class)]
    private Collection $questions;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Comment::class)]
    private Collection $comments;

    #[Assert\Length(min: 6, minMessage: "Le mot de passe doit faire au minimum 6 caracteres")]
    private ?string $newPassword = null;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Vote::class)]
    private Collection $votes;

    public function __construct()
    {
        $this->questions = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->votes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

     /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getNewPassword(): ?string
    {
        return $this->password;
    }

    public function setNewPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection<int, Question>
     */
    public function getQuestions(): Collection
    {
        return $this->questions;
    }

    public function addQuestion(Question $question): self
    {
        if (!$this->questions->contains($question)) {
            $this->questions->add($question);
            $question->setAuthor($this);
        }

        return $this;
    }

    public function removeQuestion(Question $question): self
    {
        if ($this->questions->removeElement($question)) {
            // set the owning side to null (unless already changed)
            if ($question->getAuthor() === $this) {
                $question->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }

    public function getFullname(): string {
        return $this->firstname . ' ' . $this->lastname;
    }

    /**
     * @return Collection<int, Vote>
     */
    public function getVotes(): Collection
    {
        return $this->votes;
    }

    public function addVote(Vote $vote): self
    {
        if (!$this->votes->contains($vote)) {
            $this->votes->add($vote);
            $vote->setAuthor($this);
        }

        return $this;
    }

    public function removeVote(Vote $vote): self
    {
        if ($this->votes->removeElement($vote)) {
            // set the owning side to null (unless already changed)
            if ($vote->getAuthor() === $this) {
                $vote->setAuthor(null);
            }
        }

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Image;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('firstname', TextType::class, ['label' => 'Prénom *', 'required' => false])
            ->add('lastname', TextType::class, ['label' => 'Nom *', 'required' => false])
            ->add('email', EmailType::class, ['label' => 'Email', 'required' => false])
            ->add('password', PasswordType::class, ['label' => 'Mot de passe *', 'required' => false])
            ->add('pictureFile', FileType::class, [
                'label' => 'Image de profil', 
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new Image([
                        'mimeTypesMessage' => "Veuillez uploader une image",
                        'maxSize' => '1M',
                        'maxSizeMessage' => "Votre image fait {{ size }}. La limite est de {{ limit }} {{ suffix }}"
                    ])
                ]
                
                ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Services\UploadImageService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

class UserController extends AbstractController
{
    #[Route('/user', name: 'current_user_profile')]
    #[IsGranted("IS_AUTHENTICATED_FULLY")] 
    public function currentUserProfile(Request $request, UserPasswordHasherInterface $passwordHasher, EntityManagerInterface $em, UploadImageService $uploaderPicture): Response
    {
        /**
         * @var User
         */
        $currentUser = $this->getUser();
        $profileForm = $this->createForm(UserType::class, $currentUser);
        $profileForm->remove('password');
        $profileForm->add('newPassword', PasswordType::class, ['label' => 'Nouveau mot de passe', 'required' => false]);
    
        $profileForm->handleRequest($request);
    
        if($profileForm->isSubmitted() && $profileForm->isValid()) {
            // Mis a jour des infos de l'utilisateur
            $newPassword = $currentUser->getNewPassword();
            if($newPassword) {
                $hashedNewPassword = $passwordHasher->hashPassword($currentUser, $newPassword);
                $currentUser->setPassword($hashedNewPassword);
            };

            $picture = $profileForm->get('pictureFile')->getData();

            if($picture) {
                $currentUser->setImage($uploaderPicture->uploadProfileImage($picture, $currentUser->getImage()));
            }
            $em->flush();
            $this->addFlash('succes', 'Modifications des informations sauvegardes!');
        }
        return $this->render('user/profile.html.twig', [
            'form' => $profileForm->createView()
        ]);
    }
    
    #[Route('/user/questions', name: 'show_questions')]
    #[IsGranted('IS_AUTHENTICATED_REMEMBERED')]
    public function showQuestions() {
        return $this->render('user/show_questions.html.twig');
    }
    
    #[Route('/user/comments', name: 'show_comments')]
    #[IsGranted('IS_AUTHENTICATED_REMEMBERED')]
    public function showComments() {
        return $this->render('user/show_comments.html.twig');
    }

    #[Route('/user/{id}', name: 'profile_user')]
    #[IsGranted("IS_AUTHENTICATED_REMEMBERED")]
    public function userProfile(User $user): Response
    {
        $currentUser = $this->getUser();
        if($currentUser === $user){
            return $this->redirectToRoute('current_user_profile');
        }
        return $this->render('user/show.html.twig', ['user' => $user]);
    }

}

templates/user/profile.html.twig
{% extends 'base.html.twig' %}

{% block title %}User Profile{% endblock %}

{% block body %}
    <div class="block">
        <h2 class="pb-30">Page de profil</h2>
        {{form_start(form)}}
            {{form_rest(form)}}
            <button class="btn btn-primary">Sauvegarder</button>
        {{form_end(form)}}
    </div>
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User Profile{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('question')}}
{% endblock stylesheets %}

{% block body %}
    <div class="block mb-20">
        <h2 class="pb-30">Profile de {{user.fullname}}</h2>
        <div class="d-flex flex-row-nowrap align-items-center">
            <img src="{{user.image}}" alt="User Avatar" class="mr-10 avatar-small">
            <ul>
                <li class="mb-10">
                    <strong class="mr-10">{{user.email}}</strong>
                </li>
            </ul>
        </div>
    </div>
    <div class="block mb-20">
        <h3 class="pb-30">Ces questions</h3>
        <ul>
            {% for question in user.questions %}
                <a href="{{path('show_questions', {id:question.id})}}">
                    <li class="pb-30">{{question.title}}</li>
                </a>
            {% endfor %}
        </ul>
    </div>
    <div class="block mb-2">
        <h3 class="pb-30">Ces réponses</h3>
        <ul>
            {% for comment in user.comments %}
                <a href="{{ path('show_question', {id: comment.question.id})}}">
                    <div class="d-flex flex-row-nowrap align-items-center pb-20">
                        <p>{{comment.question.title}}</p>
                        <div class="question-tag">QUESTION</div>
                    </div>
                    <li class="pb-30">{{ comment.content | slice(0, 100) }} {% if comment.content | length >= 51 %}...{% endif %}
                    </li>
                </a>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

templates/user/show_comments.html.twig
{% extends "base.html.twig" %}

{% block title %}
    Mes réponses
{% endblock title %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('question')}}
{% endblock stylesheets %}

{% block body %}
    <div class="block mb-20">
        <h3 class="pb-30">Mes réponses</h3>
        <ul>
            {% for comment in app.user.comments %}
                <a href="{{ path('show_question', {id: comment.question.id})}}">
                    <div class="d-flex flex-row-nowrap align-items-center pb-20">
                        <p>{{comment.question.title}}</p>
                        <div class="question-tag">QUESTION</div>
                    </div>
                    <li class="pb-30">{{ comment.content | slice(0, 100) }} {% if comment.content | length >= 51 %}...{% endif %}
                    </li>
                </a>
            {% endfor %}
        </ul>
    </div>
{% endblock body %}

templates/user/show_questions.html.twig
{% extends "base.html.twig" %}

{% block title %}Mes questions{% endblock %}

{% block body %}
    <div class="block mb-20">
        <h3 class="pb-30">
            Mes questions
        </h3>
        <ul>
            {% for question in app.user.questions %}
                <a href="{{path('show_question', {id: question.id})}}">
                    <li class="pb-30">{{question.title}}</li>
                </a>
            {% endfor %}
        </ul>
    </div>
{% endblock %}